extends SceneTree

func _initialize() -> void:
	var failed := 0
	failed += _check_json("res://data/buildings.json", 28)
	failed += _check_json("res://data/awards.json", 49)
	failed += _check_json("res://data/cbt.json", 18)
	failed += _check_json("res://data/cards.json", 42)
	var gear: Variant = JSON.parse_string(FileAccess.get_file_as_string("res://data/gear.json"))
	if typeof(gear) != TYPE_DICTIONARY or ((gear as Dictionary).get("items", []) as Array).size() < 12:
		push_error("gear.json missing items")
		failed += 1
	var miles: Variant = JSON.parse_string(FileAccess.get_file_as_string("res://data/milestones.json"))
	if typeof(miles) != TYPE_DICTIONARY or not miles.has("daily") or (miles["daily"] as Array).size() != 3:
		push_error("milestones.json invalid")
		failed += 1
	var shop: Variant = JSON.parse_string(FileAccess.get_file_as_string("res://data/shop.json"))
	if typeof(shop) != TYPE_DICTIONARY or not (shop as Dictionary).has("ammo") or not (shop as Dictionary).has("grenade"):
		push_error("shop.json missing vendor items")
		failed += 1
	if not (shop as Dictionary).has("catalogs"):
		push_error("shop catalogs missing")
		failed += 1
	failed += _encounters()
	var fp := get_root().get_node("FamilyProfile")
	if fp.tab_unlocked("clinic") == false or fp.tab_unlocked("run") == false:
		push_error("Clinic and Run must start unlocked")
		failed += 1
	if fp.tab_unlocked("build"):
		push_error("Build should start locked")
		failed += 1
	if Copy.LOGO != "HnT":
		failed += 1
	if Copy.CLEAR != "DOCK STREET FILED":
		push_error("missing clear copy")
		failed += 1
	if Copy.GO_SOLO != "GO ALONE" or Copy.FIRE_CLEAR != "FIRE ESCAPES FILED":
		push_error("missing solo/fire copy")
		failed += 1
	if Copy.WAITING != "WAITING FOR FATHER" or Copy.CONNECT != "CONNECT":
		push_error("missing host/join copy")
		failed += 1
	if Copy.HALL_CLEAR != "CITY HALL FILED":
		push_error("missing city hall copy")
		failed += 1
	if Copy.SKIP_FILM != "PAUSE SKIPS  ·  LIGHT ADVANCES":
		push_error("missing skip film copy")
		failed += 1
	if Copy.VERSUS != "VERSUS" or Copy.FIRED != "YOU'RE FIRED":
		push_error("missing versus copy")
		failed += 1
	if Copy.PIER_CLEAR != "INVOICE PIER FILED" or Copy.LOT_CLEAR != "INTAKE LOT FILED":
		push_error("missing pier/lot copy")
		failed += 1
	if Copy.PLAY_INTRO != "PLAY INTRO":
		push_error("missing play intro copy")
		failed += 1
	if Copy.OPTIONS != "OPTIONS" or Copy.RESET != "RESET PROGRESS":
		push_error("missing options/reset copy")
		failed += 1
	if Copy.FLOOR_CLEAR != "PROCESSING FLOOR FILED" or Copy.SKIP_BRIDGES != "SKIP INTER-ACT FILMS":
		push_error("missing floor/film copy")
		failed += 1
	if Copy.NEXT_FLOOR != "THE PROCESSING FLOOR":
		push_error("missing next floor copy")
		failed += 1
	if Copy.CLINIC_NIGHT.find("Processing Floor") < 0:
		push_error("missing clinic night copy")
		failed += 1
	var app := get_root().get_node("App")
	if app.couch != false:
		push_error("App.couch must default false so hub GO starts solo")
		failed += 1
	if app.density_coop != false:
		push_error("density must default solo")
		failed += 1
	failed += _exists("res://src/combat/snap_director.gd")
	failed += _exists("res://src/world/web_anchor.gd")
	failed += _exists("res://src/world/fire_escape.gd")
	failed += _exists("res://src/world/light_rig.gd")
	failed += _exists("res://src/world/vault_crate.gd")
	failed += _exists("res://src/shaders/wet_asphalt.gdshader")
	failed += _exists("res://src/shaders/neon_flicker.gdshader")
	failed += _exists("res://src/coop/party.gd")
	failed += _exists("res://src/levels/run_act.gd")
	failed += _exists("res://src/levels/fire_escapes.gd")
	failed += _exists("res://src/levels/neon_exchange.gd")
	failed += _exists("res://src/levels/rail_bridge.gd")
	failed += _exists("res://src/levels/city_hall.gd")
	failed += _exists("res://src/world/roof_vendor.gd")
	failed += _exists("res://src/world/street_shop.gd")
	failed += _exists("res://src/actors/mayor_raven.gd")
	failed += _exists("res://src/actors/act_boss.gd")
	failed += _exists("res://src/story/talk.gd")
	failed += _exists("res://src/story/mission_hud.gd")
	failed += _exists("res://src/story/story_book.gd")
	failed += _exists("res://src/ui/boss_card.gd")
	failed += _exists("res://src/ui/intro_flow.gd")
	failed += _exists("res://src/levels/tutorial_alley.gd")
	failed += _exists("res://src/levels/invoice_pier.gd")
	failed += _exists("res://src/levels/intake_lot.gd")
	failed += _exists("res://src/levels/group_circle.gd")
	failed += _exists("res://src/levels/waiting_room.gd")
	failed += _exists("res://src/levels/survive_act.gd")
	failed += _exists("res://src/survive/horde.gd")
	failed += _exists("res://src/survive/xp_gem.gd")
	failed += _exists("res://src/vs/versus_arena.gd")
	failed += _exists("res://src/ui/act_film.gd")
	failed += _exists("res://src/levels/processing_floor.gd")
	failed += _exists("res://src/levels/copay_orchard.gd")
	failed += _exists("res://src/levels/sleet_hour.gd")
	failed += _exists("res://src/levels/raven_grid.gd")
	failed += _exists("res://src/levels/ledger_dive.gd")
	failed += _exists("res://src/world/clinic_van.gd")
	failed += _exists("res://src/world/chase_crash.gd")
	failed += _exists("res://src/world/parkour_toy.gd")
	failed += _exists("res://src/world/smash_prop.gd")
	failed += _exists("res://src/ui/fridge_sheet.gd")
	failed += _exists("res://src/ui/streak_sheet.gd")
	failed += _exists("res://src/ui/lottery_sheet.gd")
	failed += _exists("res://src/ui/bag_sheet.gd")
	failed += _exists("res://src/ui/fax_sheet.gd")
	failed += _exists("res://src/ui/tip_sheet.gd")
	failed += _exists("res://src/ui/lost_sheet.gd")
	failed += _exists("res://src/ui/phone_sheet.gd")
	failed += _exists("res://src/ui/cooler_sheet.gd")
	failed += _exists("res://src/ui/coat_sheet.gd")
	failed += _exists("res://src/world/thrown_weapon.gd")
	failed += _exists("res://src/app/kit_book.gd")
	failed += _exists("res://data/kits.json")
	failed += _exists("res://src/actors/family_plan.gd")
	failed += _exists("res://src/ui/results_sheet.gd")
	failed += _exists("res://src/app/rarity.gd")
	failed += _exists("res://src/app/gear_book.gd")
	failed += _exists("res://src/app/cosmetics.gd")
	failed += _exists("res://src/app/weapon_book.gd")
	failed += _exists("res://src/audio/kit_sfx.gd")
	failed += _exists("res://src/world/parkour_gate.gd")
	failed += _exists("res://src/ui/hub_profile.gd")
	failed += _exists("res://src/ui/dopamine_shop.gd")
	failed += _exists("res://src/ui/research_sheet.gd")
	failed += _exists("res://src/ui/dojo_sheet.gd")
	failed += _exists("res://src/ui/patrol_sheet.gd")
	failed += _exists("res://src/ui/workshop_sheet.gd")
	failed += _exists("res://data/cosmetics.json")
	failed += _exists("res://data/dojo.json")
	failed += _exists("res://data/research.json")
	failed += _exists("res://data/tricks.json")
	failed += _exists("res://data/weapons.json")
	failed += _exists("res://data/dopamine.json")
	failed += _exists("res://data/crafts.json")
	failed += _exists("res://data/gear.json")
	failed += _exists("res://scenes/levels/act_film.tscn")
	failed += _exists("res://scenes/levels/processing_floor.tscn")
	failed += _exists("res://scenes/levels/copay_orchard.tscn")
	failed += _exists("res://scenes/levels/sleet_hour.tscn")
	failed += _exists("res://scenes/levels/raven_grid.tscn")
	failed += _exists("res://scenes/levels/ledger_dive.tscn")
	failed += _exists("res://assets/audio/music_finale.wav")
	failed += _exists("res://data/story.json")
	failed += _exists("res://scenes/levels/invoice_pier.tscn")
	failed += _exists("res://scenes/levels/intake_lot.tscn")
	failed += _exists("res://scenes/levels/versus.tscn")
	failed += _exists("res://scenes/levels/intro_flow.tscn")
	failed += _exists("res://src/net/net_session.gd")
	failed += _exists("res://src/net/rooms_server.gd")
	failed += _exists("res://assets/icon/fns.ico")
	failed += _contains("res://src/net/net_session.gd", "RoomsServer.boot")
	failed += _contains("res://src/audio/vo_bank.gd", "static func son_aaa")
	failed += _contains("res://src/net/rooms_server.gd", "HTTP_PORT := 8787")
	failed += _contains("res://src/net/rooms_server.gd", "RELAY_PORT := 8789")
	failed += _exists("res://src/ui/host_wait.gd")
	failed += _exists("res://src/ui/stamp_mark.gd")
	failed += _exists("res://src/ui/join_sheet.gd")
	failed += _exists("res://src/ui/stat_panel.gd")
	failed += _exists("res://src/input/pad_router.gd")
	failed += _exists("res://scenes/levels/fire_escapes.tscn")
	failed += _exists("res://scenes/levels/neon_exchange.tscn")
	failed += _exists("res://scenes/levels/rail_bridge.tscn")
	failed += _exists("res://scenes/levels/city_hall.tscn")
	failed += _exists("res://tools/hnt_rooms.py")
	failed += _contains("res://src/combat/snap_director.gd", "WORLD_SCALE := 0.22")
	failed += _contains("res://src/actors/fighter.gd", "STEAM_MAX := 100.0")
	failed += _contains("res://src/actors/fighter.gd", "JUMP_HEIGHT")
	failed += _contains("res://src/actors/fighter.gd", "jump-kick")
	failed += _contains("res://src/world/web_anchor.gd", "MIN_LEN := 80.0")
	failed += _contains("res://src/world/web_anchor.gd", "MAX_LEN := 280.0")
	failed += _contains("res://src/world/light_rig.gd", "MAX_POINT := 3")
	failed += _contains("res://src/levels/dock_street.gd", "ROOF_Y := 248.0")
	failed += _contains("res://src/levels/run_act.gd", "Party.encounters")
	failed += _contains("res://src/levels/run_act.gd", "Party.all_past")
	failed += _contains("res://src/app/app.gd", "var couch: bool = false")
	failed += _contains("res://src/app/app.gd", "neon_exchange")
	failed += _contains("res://src/app/app.gd", "invoice_pier")
	failed += _contains("res://src/app/app.gd", "processing_floor")
	failed += _contains("res://src/app/app.gd", "copay_orchard")
	failed += _contains("res://src/app/app.gd", "raven_grid")
	failed += _contains("res://src/app/app.gd", "ledger_dive")
	failed += _contains("res://src/app/app.gd", "sleet_hour")
	failed += _contains("res://src/app/app.gd", "act_film")
	failed += _contains("res://src/app/app.gd", "intake_lot")
	failed += _contains("res://src/app/app.gd", "func start_versus")
	failed += _contains("res://src/app/app.gd", "film_kind")
	failed += _contains("res://src/world/night_street.gd", "theme: String = \"dock\"")
	failed += _contains("res://src/levels/run_act.gd", "BossCard.present")
	failed += _contains("res://src/levels/invoice_pier.gd", "INVOICE PIER")
	failed += _contains("res://src/levels/survive_act.gd", "Horde.new")
	failed += _contains("res://src/actors/fighter.gd", "var vs_mode")
	failed += _contains("res://src/ui/hub_run.gd", "Copy.PLAY_INTRO")
	failed += _contains("res://src/ui/copy.gd", "SKIP THIS FEELING")
	failed += _contains("res://src/ui/copy.gd", "RESET PROGRESS")
	failed += _contains("res://src/ui/copy.gd", "FAMILY PROFILE")
	failed += _contains("res://src/ui/copy.gd", "QUICK PATROL")
	failed += _contains("res://src/ui/hub.gd", "_open_profile")
	failed += _contains("res://src/ui/clinic_camp.gd", "open_sheet")
	failed += _contains("res://src/app/family_profile.gd", "func start_patrol")
	failed += _contains("res://src/app/family_profile.gd", "func try_research")
	failed += _contains("res://src/app/family_profile.gd", "func try_dojo")
	failed += _contains("res://src/actors/fighter.gd", "func stumble(")
	failed += _contains("res://src/actors/fighter.gd", "var trick_boost")
	failed += _contains("res://src/actors/fighter.gd", "uppercut")
	failed += _contains("res://src/actors/punk.gd", "stomp_hits")
	failed += _contains("res://src/levels/run_act.gd", "_place_parkour")
	failed += _contains("res://src/juice/juice.gd", "func carpenter(")
	failed += _contains("res://src/juice/juice.gd", "func level_up(")
	failed += _contains("res://data/tricks.json", "KING KONG JUMPOFF")
	failed += _contains("res://src/ui/settings_sheet.gd", "RESET")
	failed += _contains("res://src/app/family_profile.gd", "func reset_progress")
	failed += _contains("res://src/coop/run_state.gd", "score_son")
	failed += _contains("res://src/app/rarity.gd", "legendary")
	failed += _contains("res://src/actors/family_plan.gd", "ARMOR STRIPPED")
	failed += _contains("res://src/ui/act_film.gd", "_advance_hard")
	failed += _contains("res://src/ui/act_film.gd", "_tint_speakers")
	failed += _contains("res://src/ui/boss_card.gd", "sting_finale")
	failed += _contains("res://src/ui/run_hud.gd", "TABLE")
	failed += _contains("res://src/app/rarity.gd", "func buy(")
	failed += _contains("res://src/world/street_shop.gd", "Rarity.buy")
	failed += _contains("res://src/world/weapon_pickup.gd", "of_pickup")
	failed += _contains("res://src/net/net_session.gd", "extra")
	failed += _contains("res://src/juice/juice.gd", "func cash_out(")
	failed += _contains("res://src/juice/juice.gd", "func toast(")
	failed += _contains("res://src/juice/juice.gd", "func unlock_logo(")
	failed += _contains("res://src/ui/hub_locker.gd", "Copy.WEAR")
	failed += _contains("res://src/combat/card_pick.gd", "Copy.SKIP")
	failed += _contains("res://src/world/light_rig.gd", "func tint_at")
	failed += _contains("res://src/world/vault_crate.gd", "func smash(")
	failed += _contains("res://src/input/pad_router.gd", "drop_in.emit(device)")
	failed += _contains("res://src/ui/hub_run.gd", "Copy.GO_SOLO")
	failed += _contains("res://src/ui/hub_run.gd", "host_wait.gd")
	failed += _contains("res://src/ui/hub_clinic.gd", "App.couch = false")
	failed += _contains("res://src/net/net_session.gd", "GAME_PORT := 24567")
	failed += _contains("res://src/ui/copy.gd", "WAITING FOR FATHER")
	failed += _contains("res://src/actors/mayor_raven.gd", "PHASE 3")
	failed += _contains("res://data/story.json", "dock_street->intake_lot")
	failed += _contains("res://src/world/chase_crash.gd", "NOOOO")
	failed += _contains("res://src/world/chase_crash.gd", "AAAA")
	failed += _contains("res://src/world/clinic_van.gd", "ramp_x")
	failed += _contains("res://src/levels/raven_grid.gd", "defer_final_boss")
	failed += _contains("res://src/world/night_street.gd", "static func ramp")
	failed += _contains("res://src/world/night_street.gd", "static func canal")
	failed += _contains("res://src/juice/juice.gd", "func smash_burst")
	failed += _contains("res://src/juice/juice.gd", "func named_slowmo")
	failed += _contains("res://src/juice/juice.gd", "func kill_cam")
	failed += _contains("res://src/actors/fighter.gd", "parry_win")
	failed += _contains("res://src/combat/snap_director.gd", "DUAL SNAP")
	failed += _contains("res://src/levels/run_act.gd", "Phone Ghost")
	failed += _contains("res://src/levels/run_act.gd", "Dumpster King")
	failed += _contains("res://src/world/smash_prop.gd", "smashables")
	failed += _contains("res://src/ui/copy.gd", "SNACK FRIDGE")
	failed += _contains("res://src/ui/hub.gd", "fridge_sheet.gd")
	failed += _contains("res://data/kits.json", "Phone Ghost")
	failed += _contains("res://data/kits.json", "Dumpster King")
	failed += _contains("res://data/kits.json", "Meter Maid")
	failed += _contains("res://data/kits.json", "Coupon Cart")
	failed += _contains("res://data/kits.json", "Ticket Skipper")
	failed += _contains("res://data/cards.json", "wall_bounce")
	failed += _contains("res://data/cards.json", "revenge_policy")
	failed += _contains("res://data/cards.json", "cart_hop")
	failed += _contains("res://src/ui/copy.gd", "REVENGE")
	failed += _contains("res://src/ui/hub.gd", "fax_sheet.gd")
	failed += _contains("res://src/ui/hub.gd", "tip_sheet.gd")
	failed += _contains("res://src/actors/fighter.gd", "revenge_win")
	failed += _contains("res://src/actors/fighter.gd", "cart_t")
	failed += _contains("res://src/actors/fighter.gd", "_try_catch")
	failed += _contains("res://src/actors/fighter.gd", "PERFECT_PARRY")
	failed += _contains("res://src/actors/punk.gd", "func _clash")
	failed += _contains("res://src/juice/juice.gd", "func revenge_flash")
	failed += _contains("res://src/juice/juice.gd", "func clash")
	failed += _contains("res://src/juice/juice.gd", "func catch_flash")
	failed += _contains("res://src/juice/juice.gd", "func geyser")
	failed += _contains("res://src/levels/run_act.gd", "Meter Maid")
	failed += _contains("res://src/world/smash_prop.gd", "cop_car")
	failed += _contains("res://src/world/smash_prop.gd", "hydrant")
	failed += _contains("res://src/world/parkour_toy.gd", "\"cart\"")
	failed += _contains("res://src/world/parkour_toy.gd", "\"awning\"")
	failed += _contains("res://data/kits.json", "Hydrant Cop")
	failed += _contains("res://data/kits.json", "Envelope Clerk")
	failed += _contains("res://data/kits.json", "Awning Acrobat")
	failed += _contains("res://data/kits.json", "Paper Boy")
	failed += _contains("res://data/kits.json", "Oil Ghost")
	failed += _contains("res://data/kits.json", "Pole Clerk")
	failed += _contains("res://data/kits.json", "Rail Rat")
	failed += _contains("res://data/kits.json", "Wall Kid")
	failed += _contains("res://data/cards.json", "weapon_catch")
	failed += _contains("res://data/cards.json", "clash_policy")
	failed += _contains("res://data/cards.json", "awning_hop")
	failed += _contains("res://data/cards.json", "oil_policy")
	failed += _contains("res://data/cards.json", "pole_vault")
	failed += _contains("res://data/cards.json", "dive_bounce")
	failed += _contains("res://src/ui/copy.gd", "CATCH")
	failed += _contains("res://src/ui/copy.gd", "CLASH")
	failed += _contains("res://src/ui/copy.gd", "TIP JAR")
	failed += _contains("res://src/ui/copy.gd", "OIL DRUM")
	failed += _contains("res://src/ui/copy.gd", "POLE SWING")
	failed += _contains("res://src/ui/copy.gd", "WALL KICK")
	failed += _contains("res://src/ui/copy.gd", "WATER COOLER")
	failed += _contains("res://src/world/smash_prop.gd", "barrel")
	failed += _contains("res://src/world/parkour_toy.gd", "\"pole\"")
	failed += _contains("res://src/actors/fighter.gd", "WALL_KICK")
	failed += _contains("res://src/actors/fighter.gd", "SLAM_BOUNCE")
	failed += _contains("res://src/juice/juice.gd", "func boom")
	failed += _contains("res://src/ui/hub.gd", "clock_sheet.gd")
	failed += _contains("res://src/world/smash_prop.gd", "manhole")
	failed += _contains("res://src/world/parkour_toy.gd", "\"hood\"")
	failed += _contains("res://src/world/parkour_toy.gd", "\"bench\"")
	failed += _contains("res://src/actors/fighter.gd", "SLIDE")
	failed += _contains("res://data/kits.json", "Hood Hopper")
	failed += _contains("res://data/kits.json", "Steam Mole")
	failed += _contains("res://data/kits.json", "Bench Clerk")
	failed += _contains("res://data/kits.json", "Slide Clerk")
	failed += _contains("res://data/cards.json", "hood_hop")
	failed += _contains("res://data/cards.json", "steam_lid")
	failed += _contains("res://data/cards.json", "slide_tax")
	failed += _exists("res://data/towers.json")
	failed += _exists("res://data/secrets.json")
	failed += _exists("res://src/world/viewpoint_tower.gd")
	failed += _exists("res://src/world/parachute_setpiece.gd")
	failed += _exists("res://src/world/secret_stash.gd")
	failed += _exists("res://src/world/wellness_shuttle.gd")
	failed += _exists("res://src/ui/cling_qte.gd")
	failed += _exists("res://src/ui/summit_talk.gd")
	failed += _exists("res://src/world/tower_book.gd")
	failed += _exists("res://scenes/levels/parachute_fall.tscn")
	failed += _exists("res://tools/balance_sim.py")
	failed += _contains("res://src/app/app.gd", "parachute_fall")
	failed += _contains("res://src/app/app.gd", "film_kind = \"parachute\"")
	failed += _contains("res://src/levels/run_act.gd", "_place_towers")
	failed += _contains("res://src/levels/run_act.gd", "_place_secrets")
	failed += _contains("res://src/levels/raven_grid.gd", "defer_final_boss")
	failed += _contains("res://src/world/chase_crash.gd", "NOOOO")
	failed += _contains("res://data/towers.json", "Do you remember that, son?")
	failed += _contains("res://data/towers.json", "Nerf war")
	failed += _contains("res://data/towers.json", "milk-carton")
	failed += _contains("res://data/towers.json", "I would never have left if I didn't have to")
	failed += _contains("res://data/cbt.json", "requires")
	failed += _contains("res://data/cbt.json", "cling_callus")
	failed += _contains("res://data/cards.json", "escape_clause")
	failed += _contains("res://data/cards.json", "landlord_void")
	failed += _contains("res://src/ui/copy.gd", "EAT AT 140M")
	failed += _contains("res://src/net/net_session.gd", "GAME_PORT := 24567")
	failed += _contains("res://src/app/app.gd", "var couch: bool = false")
	failed += _contains("res://data/secrets.json", "lemon_blackbox")
	failed += _contains("res://data/secrets.json", "valet_thermos")
	failed += _contains("res://data/secrets.json", "ice_sandwich")
	failed += _contains("res://data/secrets.json", "_extra")
	failed += _contains("res://src/ui/cling_qte.gd", "fail_shout")
	failed += _exists("res://assets/audio/vo_dad_summit.wav")
	failed += _exists("res://assets/audio/vo_son_summit.wav")
	failed += _exists("res://assets/audio/el_dad_summit.mp3")
	failed += _exists("res://assets/audio/el_son_summit.mp3")
	failed += _exists("res://assets/audio/vo_dad_skinwalker.wav")
	failed += _exists("res://assets/audio/vo_son_skinwalker.wav")
	failed += _exists("res://assets/audio/el_dad_skinwalker.mp3")
	failed += _exists("res://assets/audio/el_son_skinwalker.mp3")
	failed += _exists("res://assets/audio/sfx_whistle.wav")
	failed += _exists("res://assets/audio/sfx_gape.wav")
	failed += _contains("res://src/levels/copay_orchard.gd", "WellnessShuttle")
	failed += _contains("res://src/ui/copy.gd", "HOOD BOUNCE")
	failed += _contains("res://src/ui/copy.gd", "TIME CLOCK")
	failed += _contains("res://src/juice/juice.gd", "func hood")
	failed += _contains("res://data/story.json", "city_hall->copay_orchard")
	failed += _contains("res://data/cards.json", "invoice_void")
	failed += _contains("res://src/world/viewpoint_tower.gd", "1640.0")
	failed += _contains("res://src/world/viewpoint_tower.gd", "cinematic_on")
	failed += _contains("res://data/towers.json", "\"y\": 248")
	failed += _contains("res://src/ui/cling_qte.gd", "keep_alive")
	failed += _contains("res://src/ui/cling_qte.gd", "NetSession.tapped")
	failed += _contains("res://src/ui/summit_talk.gd", "_activate_focus")
	failed += _contains("res://src/ui/summit_talk.gd", "processing_floor")
	failed += _contains("res://src/world/parachute_setpiece.gd", "broadcast_begin")
	failed += _contains("res://src/world/parachute_setpiece.gd", "shuttle_rip")
	failed += _exists("res://src/actors/skinwalker.gd")
	failed += _exists("res://src/world/skinwalker_film.gd")
	failed += _exists("res://scenes/levels/skinwalker_film.tscn")
	failed += _contains("res://src/app/app.gd", "skinwalker_film")
	failed += _contains("res://src/app/app.gd", "film_kind = \"skinwalker\"")
	failed += _contains("res://data/story.json", "\"kind\": \"skinwalker\"")
	failed += _contains("res://src/ui/copy.gd", "THAT IS A SKINWALKER")
	failed += _contains("res://src/juice/juice.gd", "func gape")
	failed += _contains("res://src/juice/juice.gd", "func phase_flicker")
	failed += _contains("res://src/actors/skinwalker.gd", "CRAWL")
	failed += _contains("res://src/world/skinwalker_film.gd", "broadcast_begin")
	failed += _contains("res://src/world/wellness_shuttle.gd", "FILE THE RESULTS")
	failed += _contains("res://src/world/clinic_van.gd", "towers")
	failed += _contains("res://src/levels/raven_grid.gd", "_tower_blocks_chase")
	failed += _contains("res://data/weapons.json", "invoice_star")
	failed += _contains("res://data/weapons.json", "nailgun")
	failed += _contains("res://data/secrets.json", "invoice_star")
	failed += _contains("res://src/ui/copy.gd", "OPEN HOUSE")
	failed += _contains("res://src/net/net_session.gd", "RELAY_PORT := 8789")
	var boot := get_root().get_node_or_null("Boot")
	if boot:
		boot._enter_tree()
	if not InputMap.has_action("p2_snap") or not InputMap.has_action("p2_special"):
		push_error("P2 kit actions missing")
		failed += 1
	if not InputMap.has_action("p1_snap") or not InputMap.has_action("p1_dash"):
		push_error("P1 kit actions missing")
		failed += 1
	var net := get_root().get_node_or_null("NetSession")
	if net == null:
		push_error("NetSession autoload missing")
		failed += 1
	var rooms := get_root().get_node_or_null("RoomsServer")
	if rooms == null:
		push_error("RoomsServer autoload missing")
		failed += 1
	if failed > 0:
		push_error("SMOKE FAILED %d" % failed)
		quit(1)
	else:
		print("SMOKE OK")
		quit(0)


func _encounters() -> int:
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string("res://data/encounters.json"))
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("encounters.json missing")
		return 1
	var n := 0
	n += _map_counts(parsed, "dock_street", 3, 6)
	n += _map_counts(parsed, "fire_escapes", 3, 6)
	n += _map_counts(parsed, "neon_exchange", 3, 6)
	n += _map_counts(parsed, "rail_bridge", 3, 6)
	n += _map_counts(parsed, "city_hall", 3, 6)
	n += _map_counts(parsed, "invoice_pier", 3, 6)
	n += _map_counts(parsed, "intake_lot", 3, 6)
	n += _map_counts(parsed, "group_circle", 3, 6)
	n += _map_counts(parsed, "waiting_room", 3, 6)
	n += _map_counts(parsed, "processing_floor", 3, 6)
	n += _map_counts(parsed, "copay_orchard", 3, 6)
	n += _map_counts(parsed, "sleet_hour", 3, 6)
	n += _map_counts(parsed, "raven_grid", 3, 6)
	n += _map_counts(parsed, "ledger_dive", 3, 6)
	return n


func _map_counts(parsed: Variant, map_id: String, solo_n: int, coop_n: int) -> int:
	var row: Variant = (parsed as Dictionary).get(map_id, {})
	if typeof(row) != TYPE_DICTIONARY:
		push_error("%s missing in encounters" % map_id)
		return 1
	var solo: Variant = (row as Dictionary).get("solo", [])
	var coop: Variant = (row as Dictionary).get("coop", [])
	if typeof(solo) != TYPE_ARRAY or (solo as Array).size() != solo_n:
		push_error("%s solo expected %d" % [map_id, solo_n])
		return 1
	if typeof(coop) != TYPE_ARRAY or (coop as Array).size() != coop_n:
		push_error("%s coop expected %d" % [map_id, coop_n])
		return 1
	if solo_n >= coop_n:
		push_error("%s solo is not thinner than coop" % map_id)
		return 1
	return 0


func _check_json(path: String, n: int) -> int:
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	if typeof(parsed) != TYPE_ARRAY or (parsed as Array).size() != n:
		push_error("%s expected %d entries" % [path, n])
		return 1
	return 0


func _exists(path: String) -> int:
	if not FileAccess.file_exists(path):
		push_error("missing %s" % path)
		return 1
	return 0


func _contains(path: String, needle: String) -> int:
	var body := FileAccess.get_file_as_string(path)
	if not body.contains(needle):
		push_error("%s missing %s" % [path, needle])
		return 1
	return 0
