class_name Copy
extends Object

const TAB_CLINIC := "CLINIC"
const TAB_RUN := "RUN"
const TAB_BUILD := "BUILD"
const TAB_LOCKER := "LOCKER"
const TAB_AWARDS := "AWARDS"

const LOGO := "HnT"
const SUB := "REVENGE & THERAPY"
const TAGLINE := "Illegal clinic. Legal violence."

const CLAIM := "CLAIM"
const CLAIMED := "FILED"
const SKIP := "SKIP THIS FEELING"
const REROLL := "REROLL"
const WEAR := "WEAR"
const WEARING := "ON THE BODY"
const BANKED := "BANKED"
const LOCKED := "COME BACK AFTER YOU BUILD THE COUCH"
const EMPTY_LOG := "NOBODY WROTE. SHOCKING."
const GROWTH := "GROWTH UNLOCKED"
const HEALTHY := "THAT'S HEALTHY"
const INTAKE := "NAME THE PATIENTS"
const PLAY := "GO TALK TO THE LANDLORD"
const HOST := "HOST (THE SON)"
const JOIN := "JOIN (THE FATHER)"
const HOST_HINT := "One button. A room code. He texts it. You do not explain ports."
const WAITING := "WAITING FOR FATHER"
const SHARE_CODE := "Share the code. You do not need the IP."
const IP_BACKUP := "IP (BACKUP)"
const CANCEL_HOST := "CANCEL HOST"
const CONNECT := "CONNECT"
const CONNECTING := "CONNECTING…"
const PATH_DIRECT := "Direct"
const PATH_RELAY := "Relay"
const PAUSE := "SESSION PAUSED"
const FAIL := "THERAPY'S OVER"
const CLEAR := "DOCK STREET FILED"
const CLEAR_SUB := "24/7 Blood Mart is still a metaphor. You lived."
const SNAP := "SNAP"
const GROUNDED := "GROUNDED"
const DAILY := "TODAY'S COPING GOALS"
const LIFE := "FAMILY PROGRESS"
const BUILD_HINT := "Upgrade the furniture. Unlock the menus. Pretend that's healing."

const SOLO := "SOLO"
const COUCH := "COUCH 2P"
const GO_SOLO := "GO ALONE"
const GO_COUCH := "GO TOGETHER"
const JOIN_HINT := "Pad Start or keyboard P sits the other role down. Enemies do not multiply."
const SOLO_HINT := "One body. Fewer punks. Same street. Nobody has to wait."
const COUCH_HINT := "Two bodies. Full roster. Shared lives. The leash is the relationship."
const FIRE_CLEAR := "FIRE ESCAPES FILED"
const FIRE_SUB := "Roofs filed. The vendor still wants a tip."
const NEXT_MAP := "THE FIRE ESCAPES"
const GATE_SUB := "Blood Mart is a checkpoint, not a personality. Roofs are next."
const CLINIC_PLAY_SUB := "Starts solo. Couch 2P lives on the Run tab. No one has to plug in."
const NEON_CLEAR := "NEON EXCHANGE FILED"
const NEON_SUB := "The pawn shop kept the plate. You kept the pulse."
const NEXT_NEON := "NEON EXCHANGE"
const NEON_GATE := "Pawn & Plate buys your leftovers. Agents do not."
const BRIDGE_CLEAR := "RAIL BRIDGE FILED"
const BRIDGE_SUB := "The toll was violence. The receipt is a grenade."
const NEXT_BRIDGE := "RAIL BRIDGE"
const BRIDGE_GATE := "Boxcars are roofs. The street still bites."
const HALL_CLEAR := "CITY HALL FILED"
const HALL_SUB := "Mayor Raven conceded. The lights came back. The invoice did not."
const NEXT_HALL := "CITY HALL"
const HALL_GATE := "No shop. Mini before the door. Then the landlord."
const REMOTE_HINT := "Remote: The Son Hosts. The Father pastes the code and Connects. Couch 2P is still the other button."


static func come_on(father: String, son: String, who: String) -> String:
	if who == "father":
		return "COME ON, %s" % father
	return "%s, GET OFF THE ROOF" % son
