class_name Copy
extends Object

const TAB_CLINIC := "CLINIC"
const TAB_RUN := "RUN"
const TAB_BUILD := "BUILD"
const TAB_LOCKER := "LOCKER"
const TAB_AWARDS := "AWARDS"

const LOGO := "HnT"
const SUB := "REVENGE & THERAPY"
const TAGLINE := "Illegal clinic. Legal violence."

const CLAIM := "CLAIM"
const CLAIMED := "FILED"
const SKIP := "SKIP THIS FEELING"
const REROLL := "REROLL"
const WEAR := "WEAR"
const WEARING := "ON THE BODY"
const BANKED := "BANKED"
const LOCKED := "COME BACK AFTER YOU BUILD THE COUCH"
const EMPTY_LOG := "NOBODY WROTE. SHOCKING."
const GROWTH := "GROWTH UNLOCKED"
const HEALTHY := "THAT'S HEALTHY"
const INTAKE := "NAME THE PATIENTS"
const PLAY := "GO TALK TO THE LANDLORD"
const HOST := "HOST (THE SON)"
const JOIN := "JOIN (THE FATHER)"
const HOST_HINT := "One button. A room code. He texts it. You do not explain ports."
const WAITING := "WAITING FOR FATHER"
const SHARE_CODE := "Share the code. You do not need the IP."
const IP_BACKUP := "IP (BACKUP)"
const CANCEL_HOST := "CANCEL HOST"
const CONNECT := "CONNECT"
const CONNECTING := "CONNECTING…"
const PATH_DIRECT := "Direct"
const PATH_RELAY := "Relay"
const PAUSE := "SESSION PAUSED"
const FAIL := "THERAPY'S OVER"
const CLEAR := "DOCK STREET FILED"
const CLEAR_SUB := "24/7 Blood Mart is still a metaphor. You lived."
const SNAP := "SNAP"
const GROUNDED := "GROUNDED"
const DAILY := "TODAY'S COPING GOALS"
const LIFE := "FAMILY PROGRESS"
const BUILD_HINT := "Upgrade the furniture. Unlock the menus. Pretend that's healing."
const CLINIC_NIGHT := "Ten acts. Films between them. Processing Floor last. Pretend that's a treatment plan."

const SOLO := "SOLO"
const COUCH := "COUCH 2P"
const GO_SOLO := "GO ALONE"
const GO_COUCH := "GO TOGETHER"
const JOIN_HINT := "Pad Start or keyboard P sits the other role down. Enemies do not multiply."
const SOLO_HINT := "One body. Fewer punks. Same street. Nobody has to wait."
const COUCH_HINT := "Two bodies. Full roster. Shared lives. The leash is the relationship."
const FIRE_CLEAR := "FIRE ESCAPES FILED"
const FIRE_SUB := "Roofs filed. The vendor still wants a tip."
const NEXT_MAP := "THE INTAKE LOT"
const GATE_SUB := "Dock Street filed the collector. Coping hour is the lot."
const CLINIC_PLAY_SUB := "Starts solo. Couch 2P lives on the Run tab. No one has to plug in."
const NEON_CLEAR := "NEON EXCHANGE FILED"
const NEON_SUB := "The pawn shop kept the plate. You kept the pulse."
const NEON_GATE := "Pawn & Plate buys your leftovers. Agents do not."
const BRIDGE_CLEAR := "RAIL BRIDGE FILED"
const BRIDGE_SUB := "The toll was violence. The receipt is a grenade."
const NEXT_BRIDGE := "RAIL BRIDGE"
const BRIDGE_GATE := "Boxcars are roofs. The street still bites."
const HALL_CLEAR := "CITY HALL FILED"
const HALL_SUB := "Mayor Raven conceded. The lights came back. The invoice did not."
const NEXT_HALL := "CITY HALL"
const HALL_GATE := "No shop. Mini before the door. Then the landlord."
const REMOTE_HINT := "Remote: The Son Hosts. The Father pastes the code and Connects. Couch 2P is still the other button."
const SKIP_FILM := "PAUSE SKIPS  ·  LIGHT ADVANCES"
const PLAY_INTRO := "PLAY INTRO"
const VERSUS := "VERSUS"
const FIRED := "YOU'RE FIRED"
const PIER_CLEAR := "INVOICE PIER FILED"
const PIER_SUB := "Dr. Splint is a receipt. The annex still smells like copay."
const NEXT_PIER := "INVOICE PIER"
const NEXT_LOT := "THE INTAKE LOT"
const LOT_CLEAR := "INTAKE LOT FILED"
const LOT_SUB := "The horde got processed. The magnet kept the chips."
const NEXT_FIRE := "THE FIRE ESCAPES"
const CIRCLE_CLEAR := "GROUP CIRCLE FILED"
const CIRCLE_SUB := "Nobody passed the stick. You billed the courtyard."
const NEXT_CIRCLE := "GROUP CIRCLE"
const WAIT_CLEAR := "WAITING ROOM FILED"
const WAIT_SUB := "Number 88 never came. You did."
const NEXT_WAIT := "THE WAITING ROOM"
const NEXT_NEON := "NEON EXCHANGE"
const GATE_LOT := "Coping hour in the lot. Magnet the chips. Elites at 0:32."
const GATE_CIRCLE := "Share circle. Timed. Mean."
const GATE_WAIT := "Fluorescent forever. Don't sit."
const GATE_FIRE := "Roofs after the lot. Gaps with opinions."
const GATE_NEON := "Agents after the circle. Smile for the warrant."
const GATE_BRIDGE := "Boxcars are roofs. The street still bites."
const OPTIONS := "OPTIONS"
const RESET := "RESET PROGRESS"
const RESET_CONFIRM := "THIS IS GROWTH"
const RESET_NEVER := "NEVER MIND"
const RESET_BLURB := "Wipes the Family Profile. Writes a backup first. The fridge does not remember you. Host/Join ports stay."
const SKIP_BRIDGES := "SKIP INTER-ACT FILMS"
const FLOOR_CLEAR := "PROCESSING FLOOR FILED"
const FLOOR_SUB := "Director Binder is a receipt. The Family Plan is a corpse. The fridge stays."
const NEXT_FLOOR := "THE PROCESSING FLOOR"
const GATE_FLOOR := "Late act. Strip the armor. Then the patterns. Then go home."
const NEXT_ENDING := "WATCH THE ENDING"
const GATE_ENDING := "The night closes. Pause still skips a beat."


static func come_on(father: String, son: String, who: String) -> String:
	if who == "father":
		return "COME ON, %s" % father
	return "%s, GET OFF THE ROOF" % son
